#!/bin/bash
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-white\/80/bg-black\/80/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-white/bg-transparent/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-gray-50\/50/bg-transparent/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-gray-50/bg-surface/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-gray-100/bg-white\/10/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/text-gray-600/text-gray-400/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/text-gray-500/text-gray-400/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/text-gray-700/text-gray-300/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/border-gray-100/border-white\/10/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/border-gray-200/border-white\/20/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/border-black\/5/border-white\/10/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/text-primary/text-white/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-primary text-white/bg-white text-black/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/bg-primary/bg-surface/g'
find src -type f -name "*.tsx" -print0 | xargs -0 sed -i 's/hover:bg-secondary/hover:bg-white\/10/g'
